// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXtdyaK39_FxGL_VBRfqkC8WEqjf8F5Ww',
    appId: '1:740792920255:web:e0a26fe969d416437a7e0a',
    messagingSenderId: '740792920255',
    projectId: 'fir-flutter-codelab-5d866',
    authDomain: 'fir-flutter-codelab-5d866.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-5d866.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvu6fs3wZQRDSO9_-YIPby8Nfvh0_gLMg',
    appId: '1:740792920255:android:bbbe8e1cb7e9bee27a7e0a',
    messagingSenderId: '740792920255',
    projectId: 'fir-flutter-codelab-5d866',
    storageBucket: 'fir-flutter-codelab-5d866.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIpBRPXUHrdX5Z1VV4dmtjOpAEQUYR5TM',
    appId: '1:740792920255:ios:0afbb447e81acc877a7e0a',
    messagingSenderId: '740792920255',
    projectId: 'fir-flutter-codelab-5d866',
    storageBucket: 'fir-flutter-codelab-5d866.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIpBRPXUHrdX5Z1VV4dmtjOpAEQUYR5TM',
    appId: '1:740792920255:ios:0afbb447e81acc877a7e0a',
    messagingSenderId: '740792920255',
    projectId: 'fir-flutter-codelab-5d866',
    storageBucket: 'fir-flutter-codelab-5d866.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
